The CLI project.
lergor/SD pull request #1
Opened 2018-03-02 06:56 UTC by lergor

2018-04-12 17:04 UTC, yurii-litvinov requested changes
- пока что самый неожиданный результат wc:
```
> echo 123 | wc
   2    1    7
```
- нужно ещё текстовое описание архитектуры
Всё остальное очень круто

2018-04-12 17:04 UTC, yurii-litvinov commented on cli/main.py
> +    # print('\x65\x63\x68\x6F\x20\x6B\x65\x6B')
Закомментированный код не нужен, его лучше или убрать вообще, или уж раскомментировать

2018-04-12 17:04 UTC, yurii-litvinov commented on cli/src/preprocessor.py
> +        next_ix = 0
Загадо чное имя переменной. next_index? :)

2018-04-12 17:04 UTC, yurii-litvinov commented on cli/test/test_cli.py
> +        self.assertEqual(os.getcwd() + os.linesep, result.get_output())
Правильнее разбить на отдельные тесты --- принцип независимости тестов же. Если один упадёт, то все остальные всё равно запустятся, и будет понятно, что именно сломалось

2018-04-19 10:33 UTC, lergor commented on cli/main.py
> +    # print('\x65\x63\x68\x6F\x20\x6B\x65\x6B')
@yurii-litvinov, пример 'echo 123 |  wc', что вы скинули, это на Windows или Linux? У меня выдает '1 1 4'

2018-04-23 14:08 UTC, yurii-litvinov commented on cli/main.py
> +    # print('\x65\x63\x68\x6F\x20\x6B\x65\x6B')
Это на Windows. Вполне возможно, что дело в переводах строк, но пока ни у кого так не было :)

2018-04-27 22:47 UTC, lergor commented on cli/test/test_cli.py
> +        self.assertEqual(os.getcwd() + os.linesep, result.get_output())
@yurii-litvinov исправила баг, добавила описание

2018-05-26 13:08 UTC, yurii-litvinov approved these changes
👍

2018-06-19 00:42 UTC, merged