Roguelike
lergor/SD pull request #3
Opened 2018-06-03 02:53 UTC by lergor

2018-06-03 17:12 UTC, yurii-litvinov requested changes
Да, видел этот туториал, он более чем ок для этой задачи. Но надо ещё диаграмму классов, раз уж пришлось с туториалом разбираться, и, если успеете, хоть один юнит-тест

2018-06-03 17:12 UTC, yurii-litvinov commented on roguelike/roguelike_info.log
> +input_handler   INFO   Pressed: 1 1
Это, наверное, лишнее

2018-06-09 10:52 UTC, yurii-litvinov approved these changes
Ага, тесты и диаграмма появились, зачтена

2018-06-09 11:05 UTC, yurii-litvinov requested changes
Надо ещё Architectural drivers, и диаграмму классов поправить, убрав лишние поля и ассоциации с enum-ами

2018-06-09 11:05 UTC, yurii-litvinov commented on roguelike/docs/design_document.md
> +## What can be extended
Тут ожидались общие сведения о системе :) Да, они есть в Readme, но диздок на то и диздок, чтобы быть полным источником знаний о системе

2018-06-09 11:05 UTC, yurii-litvinov commented on roguelike/docs/design_document.md
> +    MENU, INFO, PLAYER_TURN, ENEMY_TURN, LEVEL_UP, CHARACTER_SCREEN, SHOW_INVENTORY, DROP_INVENTORY, PLAYER_DEAD, EXIT.
Ассоциации с enum-ами не рисуются, к тому же у Game есть поля state и previous_state, которые дублируют информацию, показываемую ассоциацией

2018-06-09 11:05 UTC, yurii-litvinov commented on roguelike/docs/design_document.md
> +- **InputHandler** takes each user input which is a key that was pressed and converts
А тут наоборот, поле в классе Game избыточно, потому что ассоциация есть и она содержит всю необходимую информацию.

2018-06-09 11:05 UTC, yurii-litvinov commented on roguelike/docs/design_document.md
> +The *UIMaster* draws every object of the game by interacting with the computer screen.<br/>
Диаграмма компонентов не соответствует ни диаграмме классов, ни исходному коду (там разбиение на папки просто другое). Надо либо сгруппирвоать классы на диаграмме по компонентам (можно по пакетам, соответствующим компоненте), либо диаграмму компонентов поправить

2018-06-19 12:20 UTC, lergor commented on roguelike/docs/design_document.md
> +- **InputHandler** takes each user input which is a key that was pressed and converts
Извините, я запуталась. То есть можно убрать ассоциацию GameStates и Game, потому что поля содержат информацию?
А стоит ли добавить зависимость InputHandler от GameStates?

2018-06-19 14:44 UTC, merged